language: node_js

node_js:
  - 14

script:
  - yarn build

after_success:
  - bash .travis/docs.sh

deploy:
  provider: npm
  email: apixelvisualsofficial@gmail.com
  api_key:
    secure: 1wLmX7NtFTBzrqaNN4wvDjBMelEGekTHpVj/oXFO2x2jzoY1RRxF7yruOuNDn8yaLxsE7MdV5sgWkGOYj+w0bQs66XStv74MKRWLw+HGNfl1xJTZgEAN99u92Uc/5XLeHFfwok2ly2lnlStmeLRq1mPEVqHi+zKlxK+tGkSgLaGgsgGHUtVQQh9CasvIlDXl04SQu3ZRYqm5OJMo4nx97wtw5d890uPevs1lrNVsx12cjCPzZ0EskJ85vDrAqQynWzQjmhk1hRt3Dz06qKms28EtrFrLkt3DQliUfK7Z0rZYekK/MY4KK/BJ7+DAPxGoC3oT9DaqRajCn2TiJVSq7nc8XS7M5iKcD5/64IvlLd7yk6+o05maSP48R61PoCGso8W/ghfKm4ZlFITgLvcuoRStgebikeg/lO5P06kA8lZKkUumaqlCnRy4J11RhkT0AJhzUsU5J3+gIADhQmQsT3+0f8GyAft33BsqqVpNCxUXq3lzXDl9I7N8t6eFt0Cdhm/YAw2nJHsdSV5dY6gi4kagqVGUhsT6KkZT99e6o5vZ9eDfBnKFSQ4ZSj/rCvowPduF/HOXNNQj5ARSZxmit7xuFmmgHPVKCAcEMsDv890SSGiEHCZ2OUmbvbyXR4MAu7nEdd/A8asjbcTkh+GeYH4A1nu0k78xFHWK6BG3ERc=
  on:
    repo: aeracord/aeracord
    branch: master
    tags: true
  skip_cleanup: true